### PR TITLE
Add CherryPy + Mako Python stack boilerplate.

### PR DESCRIPTION
**Pull request by kdeldycke**
Add a new Python stack boilerplate based on CherryPy + Mako.

### CODE REVIEW

**Comment by melvin0008** [comment]
Thanks!

**Comment by kdeldycke** [comment]
Do you want me to adjust anything before my PR is considered ready for inclusion?

**Comment by melvin0008** [comment]
No. This is great. Thanks :+1:

**Comment by kdeldycke** [comment]
Thanks for the quick merge! :)

**Pull request merged**
